artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.dropbox.com/scl/fi/3y2gtqoasov838x448px1/paddy-disease-classification.zip?rlkey=172azgs486lrnc5svahnzplgg&st=qqge4iuw&dl=1
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
